-- Criação da Dimensão Aluno
CREATE TABLE CEFET_PRODUCAO.DBO.DimALUNO (
    ID_ALUNO INT IDENTITY(1,1) PRIMARY KEY,
    NOME_ALUNO NVARCHAR(255) NOT NULL,
    MATRICULA_ALUNO NVARCHAR(50) NOT NULL,
    ANO_INICIO INT NOT NULL
);

-- Criação da Dimensão Matéria
CREATE TABLE CEFET_PRODUCAO.DBO.DimMATERIA (
    ID_MATERIA INT IDENTITY(1,1) PRIMARY KEY,
    NOME_MATERIA NVARCHAR(255) NOT NULL,
    TIPO_MATERIA NVARCHAR(50) NOT NULL,
	HORA_AULA INT NOT NULL
);

-- Criação da Dimensão Tempo
CREATE TABLE CEFET_PRODUCAO.DBO.DimTEMPO (
    ID_TEMPO INT IDENTITY(1,1) PRIMARY KEY,
    DATA NVARCHAR(6) NOT NULL,
    ANO INT NOT NULL,
    SEMESTRE INT NOT NULL,
);

-- Criação da Tabela de Fatos Histórico Estudantil
CREATE TABLE FatoHISTORICO_ESTUDANTIL (
    ID_FATO INT IDENTITY(1,1) PRIMARY KEY,
    ID_ALUNO INT FOREIGN KEY REFERENCES DimAluno(ID_Aluno),
    ID_MATERIA INT FOREIGN KEY REFERENCES DimMateria(ID_Materia),
    ID_TEMPO INT FOREIGN KEY REFERENCES DimTempo(ID_Tempo),
    HORAS_REALIZADAS INT NOT NULL,
    --HORAS_PENDENTES INT NOT NULL,
    NOTA_MATERIA FLOAT,
    STATUS_MATERIA NVARCHAR(50) NOT NULL
);

CREATE TABLE DimStatus (
    ID_STATUS INT IDENTITY(0,1) PRIMARY KEY,
    STATUS NVARCHAR(50) NOT NULL
);

CREATE TABLE DimREQUISITOS (
    ID_REQUISITO INT IDENTITY(1,1) PRIMARY KEY,
    ID_MATERIA INT FOREIGN KEY REFERENCES DimMateria(ID_Materia),
	PRE_REQUISITO INT,
	CO_REQUISITO INT
);

CREATE TABLE DimPROXIMOSEMESTRE (
	ID_HORARIO INT IDENTITY(1,1) PRIMARY KEY,
    ID_MATERIA INT,
    TIPO_MATERIA NVARCHAR(100),
    HORARIO NVARCHAR(100),
	ANO NVARCHAR(6)
);