

CREATE PROCEDURE PROXIMO_SEMESTRE(

@MATRICULA NVARCHAR(100)

) AS

IF OBJECT_ID('#TEMP') IS NOT NULL
    DROP TABLE #TEMP;

SELECT A.*, C.NOME_MATERIA, D.DATA, C.ID_MATERIA
INTO #TEMP
FROM DimALUNO (NOLOCK) A
JOIN FatoHISTORICO_ESTUDANTIL (NOLOCK) B ON A.ID_ALUNO = B.ID_ALUNO
JOIN DimMATERIA (NOLOCK) C ON B.ID_MATERIA = C.ID_MATERIA
JOIN DimTEMPO (NOLOCK) D ON D.ID_TEMPO = B.ID_TEMPO
WHERE A.MATRICULA_ALUNO = @MATRICULA
AND EXISTS (SELECT *
					FROM DIMPROXIMOSEMESTRE (NOLOCK) X WHERE X.ID_MATERIA = C.ID_MATERIA)

IF OBJECT_ID('#TIPO_SEMESTRE') IS NOT NULL
    DROP TABLE #TIPO_SEMESTRE;

SELECT DISTINCT A.*, C.NOME_MATERIA, E.*,
CASE
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 0 THEN 2
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 1 AND SUBSTRING(A.ANO, 6, 2) = 1 THEN 3
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 1 AND SUBSTRING(A.ANO, 6, 2) = 2 THEN 4
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 2 AND SUBSTRING(A.ANO, 6, 2) = 1 THEN 5
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 2 AND SUBSTRING(A.ANO, 6, 2) = 2 THEN 6
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 3 AND SUBSTRING(A.ANO, 6, 2) = 1 THEN 7
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 3 AND SUBSTRING(A.ANO, 6, 2) = 2 THEN 8
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 4 AND SUBSTRING(A.ANO, 6, 2) = 1 THEN 9
WHEN SUBSTRING(A.ANO, 1, 4) - E.ANO_INICIO = 4 AND SUBSTRING(A.ANO, 6, 2) = 2 THEN 10
ELSE 10
END AS VALIDANDO
INTO #TIPO_SEMESTRE
FROM DimProximoSemestre (NOLOCK) A
JOIN DimMATERIA (NOLOCK) C ON A.ID_MATERIA = C.ID_MATERIA
JOIN FatoHISTORICO_ESTUDANTIL (NOLOCK) D ON C.ID_MATERIA = D.ID_MATERIA
JOIN DimALUNO (NOLOCK) E ON D.ID_ALUNO = E.ID_ALUNO
JOIN #TEMP F ON E.ID_ALUNO = F.ID_ALUNO
WHERE EXISTS (SELECT *
					FROM #TEMP B WHERE A.ID_MATERIA = B.ID_MATERIA
									)
AND D.STATUS_MATERIA = 1

IF OBJECT_ID('#MATERIAS_POSSIVEIS') IS NOT NULL
    DROP TABLE #MATERIAS_POSSIVEIS;

SELECT A.*
INTO #MATERIAS_POSSIVEIS
FROM DimProximoSemestre (NOLOCK) A
LEFT JOIN #TIPO_SEMESTRE (NOLOCK) C ON A.ID_MATERIA = C.ID_MATERIA
WHERE NOT EXISTS (SELECT * FROM
					#TEMP B WHERE A.ID_MATERIA = B.ID_MATERIA)
AND A.TIPO_MATERIA <= ISNULL(C.VALIDANDO, (SELECT MAX(VALIDANDO) FROM #TIPO_SEMESTRE))

SELECT A.*, X.HORARIO
FROM (
	SELECT *, ROW_NUMBER() OVER (PARTITION BY HORARIO ORDER BY ID_MATERIA) N
	FROM #MATERIAS_POSSIVEIS
	)X
	JOIN DimMATERIA (NOLOCK) A ON X.ID_MATERIA = A.ID_MATERIA
WHERE X.N = 1

DROP TABLE #TEMP
DROP TABLE #TIPO_SEMESTRE
DROP TABLE #MATERIAS_POSSIVEIS