DROP TABLE #TEMP

SELECT A.ID_FATO, D.NOME_ALUNO, D.ANO_INICIO, B.DATA, C.NOME_MATERIA, A.NOTA_MATERIA, A.STATUS_MATERIA, E.STATUS, C.HORA_AULA, C.TIPO_MATERIA,
CASE 
WHEN C.TIPO_MATERIA = 1 THEN CONVERT(NVARCHAR, D.ANO_INICIO) + '.1'
WHEN C.TIPO_MATERIA = 2 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO = 0 THEN SUBSTRING(B.DATA, 1, 4) + '.2'
WHEN C.TIPO_MATERIA = 2 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO > 0 THEN B.DATA
WHEN C.TIPO_MATERIA = 2 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 0 THEN CONVERT(NVARCHAR, D.ANO_INICIO) +'.2'
WHEN C.TIPO_MATERIA = 3 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO >= 1 THEN B.DATA
WHEN C.TIPO_MATERIA = 3 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 1 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 1) +'.1'
WHEN C.TIPO_MATERIA = 4 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO = 1 THEN SUBSTRING(B.DATA, 1, 4) + '.2'
WHEN C.TIPO_MATERIA = 4 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO > 1 THEN B.DATA
WHEN C.TIPO_MATERIA = 4 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 1 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 1) +'.2'
WHEN C.TIPO_MATERIA = 5 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO >= 2 THEN B.DATA
WHEN C.TIPO_MATERIA = 5 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 2 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 2) +'.1'
WHEN C.TIPO_MATERIA = 6 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO = 2 THEN SUBSTRING(B.DATA, 1, 4) + '.2'
WHEN C.TIPO_MATERIA = 6 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO > 2 THEN B.DATA
WHEN C.TIPO_MATERIA = 6 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 2 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 2) +'.2'
WHEN C.TIPO_MATERIA = 7 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO >= 3 THEN B.DATA
WHEN C.TIPO_MATERIA = 7 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 3 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 3) +'.1'
WHEN C.TIPO_MATERIA = 8 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO = 3 THEN SUBSTRING(B.DATA, 1, 4) + '.2'
WHEN C.TIPO_MATERIA = 8 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO > 3 THEN B.DATA
WHEN C.TIPO_MATERIA = 8 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 3 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 3) +'.2'
WHEN C.TIPO_MATERIA = 9 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO >= 4 THEN B.DATA
WHEN C.TIPO_MATERIA = 9 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 4 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 4) +'.1'
WHEN C.TIPO_MATERIA = 10 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO = 4 THEN SUBSTRING(B.DATA, 1, 4) + '.2'
WHEN C.TIPO_MATERIA = 10 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO > 4 THEN B.DATA
WHEN C.TIPO_MATERIA = 10 AND SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 4 THEN CONVERT(NVARCHAR, D.ANO_INICIO + 4) +'.2'
END AS CALCULO_ANO
--INTO #TEMP
FROM CEFET_PRODUCAO.DBO.FatoHISTORICO_ESTUDANTIL (NOLOCK) A
JOIN CEFET_PRODUCAO.DBO.DimTEMPO (NOLOCK) B ON A.ID_TEMPO = B.ID_TEMPO
JOIN CEFET_PRODUCAO.DBO.DimMateria (NOLOCK) C ON C.ID_MATERIA = A.ID_MATERIA
JOIN CEFET_PRODUCAO.DBO.DimAluno (NOLOCK) D ON D.ID_ALUNO = A.ID_ALUNO
JOIN CEFET_PRODUCAO.DBO.DimStatus (NOLOCK) E ON E.ID_STATUS = A.STATUS_MATERIA



--============================================ DATA DE CURSO DA MATERIA MENOR Q A DATA DE INGRESSAO ===============================
DELETE A FROM
CEFET_PRODUCAO.DBO.FatoHISTORICO_ESTUDANTIL (NOLOCK) A
JOIN CEFET_PRODUCAO.DBO.DimTEMPO (NOLOCK) B ON A.ID_TEMPO = B.ID_TEMPO
JOIN CEFET_PRODUCAO.DBO.DimMateria (NOLOCK) C ON C.ID_MATERIA = A.ID_MATERIA
JOIN CEFET_PRODUCAO.DBO.DimAluno (NOLOCK) D ON D.ID_ALUNO = A.ID_ALUNO
JOIN CEFET_PRODUCAO.DBO.DimStatus (NOLOCK) E ON E.ID_STATUS = A.STATUS_MATERIA
WHERE SUBSTRING(B.DATA, 1, 4) - D.ANO_INICIO < 0

BEGIN TRAN --COMMIT

DELETE C
--SELECT *
FROM #TEMP A
LEFT JOIN DimTEMPO B ON A.CALCULO_ANO = B.DATA
JOIN FatoHISTORICO_ESTUDANTIL C ON A.ID_FATO = C.ID_FATO
WHERE B.ID_TEMPO IS NULL


SELECT TEMP.*, B.ID_TEMPO
FROM CEFET_PRODUCAO.DBO.FatoHISTORICO_ESTUDANTIL (NOLOCK) A
JOIN CEFET_PRODUCAO.DBO.DimTEMPO (NOLOCK) B ON A.ID_TEMPO = B.ID_TEMPO
JOIN CEFET_PRODUCAO.DBO.DimMateria (NOLOCK) C ON C.ID_MATERIA = A.ID_MATERIA
JOIN CEFET_PRODUCAO.DBO.DimAluno (NOLOCK) D ON D.ID_ALUNO = A.ID_ALUNO
JOIN CEFET_PRODUCAO.DBO.DimStatus (NOLOCK) E ON E.ID_STATUS = A.STATUS_MATERIA
JOIN #TEMP TEMP ON TEMP.CALCULO_ANO = B.DATA

SELECT * FROM
DIMALUNO

--DROP TABLE #TEMP
SELECT 
A.ID_FATO,
D.ID_ALUNO, 
C.ID_MATERIA, 
D.NOME_ALUNO, 
B.DATA, 
C.NOME_MATERIA, 
A.NOTA_MATERIA, 
A.STATUS_MATERIA, 
E.STATUS,
DUPRANK = ROW_NUMBER() OVER (PARTITION BY D.ID_ALUNO, C.ID_MATERIA, B.DATA ORDER BY D.ID_ALUNO, C.ID_MATERIA, B.DATA)
--INTO #TEMP
FROM CEFET_PRODUCAO.DBO.FatoHISTORICO_ESTUDANTIL (NOLOCK) A
JOIN CEFET_PRODUCAO.DBO.DimTEMPO (NOLOCK) B ON A.ID_TEMPO = B.ID_TEMPO
JOIN CEFET_PRODUCAO.DBO.DimMateria (NOLOCK) C ON C.ID_MATERIA = A.ID_MATERIA
JOIN CEFET_PRODUCAO.DBO.DimAluno (NOLOCK) D ON D.ID_ALUNO = A.ID_ALUNO
JOIN CEFET_PRODUCAO.DBO.DimStatus (NOLOCK) E ON E.ID_STATUS = A.STATUS_MATERIA
ORDER BY NOME_ALUNO, C.ID_MATERIA, B.DATA

BEGIN TRAN --COMMIT

DELETE C
--SELECT *
FROM #TEMP A
JOIN FatoHISTORICO_ESTUDANTIL C ON A.ID_FATO = C.ID_FATO
WHERE A.DUPRANK > 1

--DROP TABLE #TEMP
SELECT 
A.ID_FATO,
D.ID_ALUNO, 
C.ID_MATERIA, 
D.NOME_ALUNO, 
B.DATA, 
C.NOME_MATERIA, 
A.NOTA_MATERIA, 
A.STATUS_MATERIA, 
E.STATUS,
DUPRANK = ROW_NUMBER() OVER (PARTITION BY D.ID_ALUNO, C.ID_MATERIA ORDER BY B.DATA)
INTO #TEMP
FROM CEFET_PRODUCAO.DBO.FatoHISTORICO_ESTUDANTIL (NOLOCK) A
JOIN CEFET_PRODUCAO.DBO.DimTEMPO (NOLOCK) B ON A.ID_TEMPO = B.ID_TEMPO
JOIN CEFET_PRODUCAO.DBO.DimMateria (NOLOCK) C ON C.ID_MATERIA = A.ID_MATERIA
JOIN CEFET_PRODUCAO.DBO.DimAluno (NOLOCK) D ON D.ID_ALUNO = A.ID_ALUNO
JOIN CEFET_PRODUCAO.DBO.DimStatus (NOLOCK) E ON E.ID_STATUS = A.STATUS_MATERIA
ORDER BY NOME_ALUNO, C.ID_MATERIA, B.DATA

BEGIN TRAN --COMMIT

DELETE C
--SELECT A.*
FROM #TEMP A
JOIN FatoHISTORICO_ESTUDANTIL C ON A.ID_FATO = C.ID_FATO
LEFT JOIN #TEMP2 B ON B.ID_FATO = C.ID_FATO
WHERE A.DUPRANK > B.DUPRANK 

SELECT * FROM
#TEMP A
LEFT JOIN #TEMP2 B ON A.ID_ALUNO = B.ID_ALUNO AND A.ID_MATERIA = B.ID_MATERIA
WHERE A.DUPRANK > ISNULL(B.DUPRANK, 0)
AND A.STATUS <> 'APROVADO'